using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[System.Flags]
public enum PreviewWorldRebuildScope { None=0, Tectonics=1, Climate=2, Hydrology=4, Biomes=8, All=15 }

public struct MenuPlanetPreviewWorldInputs { public float seed,landScale,landThreshold,elevation,temperature,moisture,moistureResponseScale,temperatureHumidityInfluence,climateNoiseStrength,coastWetnessStrength,continentalDrynessStrength,continentalTemperatureStrength,rainShadowStrength,orographicWetnessStrength,orographicSampleOffset,seasonalityStrength,biomeProvinceStrength,biomeCompetitionSharpness,iceCapSize; public int landPresetIndex,waterwaysPreset; }

public class MenuPlanetPreviewWorldGenerator : MonoBehaviour {
    [SerializeField] int mapWidth=1024,mapHeight=512; [SerializeField] float regenerationDelay=0.15f;
    public Texture2D TectonicSurfaceTexture{get;private set;} public Texture2D TectonicBoundaryTexture{get;private set;} public Texture2D TectonicCrustTexture{get;private set;} public Texture2D ClimateTexture{get;private set;} public Texture2D HydrologyMaskTexture{get;private set;} public Texture2D BiomeWeights0Texture{get;private set;} public Texture2D BiomeWeights1Texture{get;private set;} public Texture2D BiomeWeights2Texture{get;private set;}
    public event System.Action WorldTexturesUpdated;
    MenuPlanetPreviewWorldInputs inputs; PreviewWorldRebuildScope pending; float scheduledAt=-1;
    NativeArray<float> continentality;
    public void SetInputs(MenuPlanetPreviewWorldInputs v)=>inputs=v;
    public void RequestRebuild(PreviewWorldRebuildScope scope,bool immediate=false){pending|=ExpandDependencies(scope); if(immediate) Flush(); else scheduledAt=Time.time+regenerationDelay;}
    void Update(){ if(scheduledAt>0 && Time.time>=scheduledAt) Flush(); }
    void Flush(){scheduledAt=-1; var s=pending; pending=0; if(s==PreviewWorldRebuildScope.None) return; GenerateRequestedStages(s);}
    private PreviewWorldRebuildScope ExpandDependencies(PreviewWorldRebuildScope requested){ if((requested&PreviewWorldRebuildScope.Tectonics)!=0) return PreviewWorldRebuildScope.All; if((requested&PreviewWorldRebuildScope.Climate)!=0) return PreviewWorldRebuildScope.Climate|PreviewWorldRebuildScope.Hydrology|PreviewWorldRebuildScope.Biomes; if((requested&PreviewWorldRebuildScope.Hydrology)!=0) return PreviewWorldRebuildScope.Hydrology|PreviewWorldRebuildScope.Biomes; if((requested&PreviewWorldRebuildScope.Biomes)!=0) return PreviewWorldRebuildScope.Biomes; return 0;}
    private void GenerateRequestedStages(PreviewWorldRebuildScope scope){ if((scope&PreviewWorldRebuildScope.Tectonics)!=0) GenerateTectonics(); if((scope&PreviewWorldRebuildScope.Climate)!=0) GenerateClimate(); if((scope&PreviewWorldRebuildScope.Hydrology)!=0) GenerateHydrology(); if((scope&PreviewWorldRebuildScope.Biomes)!=0) GenerateBiomes(); WorldTexturesUpdated?.Invoke(); }
    void Ensure(ref Texture2D t,string n){ if(t!=null&&t.width==mapWidth&&t.height==mapHeight) return; if(t!=null) Destroy(t); t=new Texture2D(mapWidth,mapHeight,TextureFormat.RGBA32,false,true){name=n,wrapMode=TextureWrapMode.Repeat,filterMode=FilterMode.Bilinear}; }
    void GenerateTectonics(){ Ensure(ref TectonicSurfaceTexture,"MenuTectonicSurface"); Ensure(ref TectonicBoundaryTexture,"MenuTectonicBoundary"); Ensure(ref TectonicCrustTexture,"MenuTectonicCrust"); int n=mapWidth*mapHeight; var s=new NativeArray<Color32>(n,Allocator.TempJob); var b=new NativeArray<Color32>(n,Allocator.TempJob); var c=new NativeArray<Color32>(n,Allocator.TempJob); new TectJob{width=mapWidth,height=mapHeight,seed=inputs.seed,landScale=inputs.landScale,landThreshold=inputs.landThreshold,elevation=inputs.elevation,surf=s,bound=b,crust=c}.Schedule(n,128).Complete(); TectonicSurfaceTexture.SetPixelData(s,0); TectonicBoundaryTexture.SetPixelData(b,0); TectonicCrustTexture.SetPixelData(c,0); TectonicSurfaceTexture.Apply(false,false); TectonicBoundaryTexture.Apply(false,false); TectonicCrustTexture.Apply(false,false); s.Dispose(); b.Dispose(); c.Dispose(); RebuildContinentality(); }
    void RebuildContinentality(){ int n=mapWidth*mapHeight; if(continentality.IsCreated) continentality.Dispose(); continentality=new NativeArray<float>(n,Allocator.Persistent); var q=new System.Collections.Generic.Queue<int>(); var raw=TectonicSurfaceTexture.GetRawTextureData<Color32>(); for(int i=0;i<n;i++){ if(raw[i].r<128){continentality[i]=0; q.Enqueue(i);} else continentality[i]=9999; } int[] dirs={-1,1,-mapWidth,mapWidth}; while(q.Count>0){ int i=q.Dequeue(); int x=i%mapWidth,y=i/mapWidth; float d=continentality[i]+1; int l=y*mapWidth+((x-1+mapWidth)%mapWidth),r=y*mapWidth+((x+1)%mapWidth); if(d<continentality[l]){continentality[l]=d;q.Enqueue(l);} if(d<continentality[r]){continentality[r]=d;q.Enqueue(r);} if(y>0){int u=i-mapWidth; if(d<continentality[u]){continentality[u]=d;q.Enqueue(u);}} if(y<mapHeight-1){int dn=i+mapWidth; if(d<continentality[dn]){continentality[dn]=d;q.Enqueue(dn);}} } float max=1; for(int i=0;i<n;i++) if(continentality[i]>max && continentality[i]<9999) max=continentality[i]; for(int i=0;i<n;i++) continentality[i]=math.saturate(continentality[i]/max); }
    void GenerateClimate(){ if(TectonicSurfaceTexture==null) return; Ensure(ref ClimateTexture,"MenuClimate"); var tect=new NativeArray<Color32>(TectonicSurfaceTexture.GetRawTextureData<Color32>().ToArray(),Allocator.TempJob); var outp=new NativeArray<Color32>(mapWidth*mapHeight,Allocator.TempJob); new ClimateJob{width=mapWidth,height=mapHeight,temperature=inputs.temperature,moisture=inputs.moisture,climateNoiseStrength=inputs.climateNoiseStrength,coastWetnessStrength=inputs.coastWetnessStrength,continentalDrynessStrength=inputs.continentalDrynessStrength,continentalTemperatureStrength=inputs.continentalTemperatureStrength,seasonalityStrength=inputs.seasonalityStrength,tect=tect,cont=continentality,outp=outp}.Schedule(mapWidth*mapHeight,128).Complete(); ClimateTexture.SetPixelData(outp,0); ClimateTexture.Apply(false,false); tect.Dispose(); outp.Dispose(); }
    void GenerateHydrology(){ if(TectonicSurfaceTexture==null||ClimateTexture==null){ Debug.LogError("[MenuPlanetPreviewWorldGenerator] Missing tectonic or climate data; hydrology generation aborted."); return;} Ensure(ref HydrologyMaskTexture,"MenuHydrology"); HydrologyMaskTexture.SetPixels32(new Color32[mapWidth*mapHeight]); HydrologyMaskTexture.Apply(false,false); }
    void GenerateBiomes(){ if(TectonicSurfaceTexture==null||ClimateTexture==null||HydrologyMaskTexture==null) return; Ensure(ref BiomeWeights0Texture,"MenuBiome0"); Ensure(ref BiomeWeights1Texture,"MenuBiome1"); Ensure(ref BiomeWeights2Texture,"MenuBiome2"); int n=mapWidth*mapHeight; var tect=new NativeArray<Color32>(TectonicSurfaceTexture.GetRawTextureData<Color32>().ToArray(),Allocator.TempJob); var climate=new NativeArray<Color32>(ClimateTexture.GetRawTextureData<Color32>().ToArray(),Allocator.TempJob); var hydro=new NativeArray<Color32>(HydrologyMaskTexture.GetRawTextureData<Color32>().ToArray(),Allocator.TempJob); var o0=new NativeArray<Color32>(n,Allocator.TempJob); var o1=new NativeArray<Color32>(n,Allocator.TempJob); var o2=new NativeArray<Color32>(n,Allocator.TempJob); new BiomeJob{tect=tect,climate=climate,hydro=hydro,o0=o0,o1=o1,o2=o2,iceCap=inputs.iceCapSize}.Schedule(n,128).Complete(); BiomeWeights0Texture.SetPixelData(o0,0);BiomeWeights1Texture.SetPixelData(o1,0);BiomeWeights2Texture.SetPixelData(o2,0);BiomeWeights0Texture.Apply(false,false);BiomeWeights1Texture.Apply(false,false);BiomeWeights2Texture.Apply(false,false); tect.Dispose();climate.Dispose();hydro.Dispose();o0.Dispose();o1.Dispose();o2.Dispose(); }
    public void Release(){ if(continentality.IsCreated) continentality.Dispose(); foreach(var t in new[]{TectonicSurfaceTexture,TectonicBoundaryTexture,TectonicCrustTexture,ClimateTexture,HydrologyMaskTexture,BiomeWeights0Texture,BiomeWeights1Texture,BiomeWeights2Texture}) if(t!=null) Destroy(t); pending=0; }
    static byte ToByte(float v)=> (byte)math.clamp(math.round(math.saturate(v)*255f),0f,255f);
    [BurstCompile] struct TectJob:IJobParallelFor{ public int width,height; public float seed,landScale,landThreshold,elevation; public NativeArray<Color32> surf,bound,crust; public void Execute(int i){int x=i%width,y=i/width; float lat=math.abs(((y+0.5f)/height)*2f-1f); float n=(math.sin((x+seed)*0.02f)+math.cos((y-seed)*0.03f))*0.25f+0.5f; float land=math.saturate(n-(landThreshold-0.5f)); float h=math.saturate(land*(0.4f+0.6f*(1f-lat))+ (elevation-0.5f)*0.2f); float m=math.saturate(h*land); surf[i]=new Color32(ToByte(land),ToByte(h),ToByte(m),ToByte((1f-land)*0.5f)); bound[i]=new Color32(ToByte(n),ToByte(math.saturate(1f-land)),ToByte(m*0.7f),ToByte((1f-land)*0.3f)); crust[i]=new Color32(ToByte(land),ToByte(1f-land),ToByte((1f-land)*(1f-h)),ToByte(h)); }}
    [BurstCompile] struct ClimateJob:IJobParallelFor{ public int width,height; public float temperature,moisture,climateNoiseStrength,coastWetnessStrength,continentalDrynessStrength,continentalTemperatureStrength,seasonalityStrength; [ReadOnly] public NativeArray<Color32> tect; [ReadOnly] public NativeArray<float> cont; public NativeArray<Color32> outp; public void Execute(int i){int y=i/width; float lat=math.abs(((y+0.5f)/height)*2f-1f); float l=tect[i].r/255f; float h=tect[i].g/255f; float c=cont[i]; float t=math.saturate((1f-lat)+(temperature-0.5f)*0.35f-h*0.4f+c*continentalTemperatureStrength*(temperature-0.5f)); float m=math.saturate(moisture + (1f-c)*coastWetnessStrength*l - c*continentalDrynessStrength*l); float s=math.saturate(lat*0.75f + c*0.45f + climateNoiseStrength*0.1f); outp[i]=new Color32(ToByte(t),ToByte(m),ToByte(c),ToByte(s)); }}
    [BurstCompile] struct BiomeJob:IJobParallelFor{ [ReadOnly] public NativeArray<Color32> tect,climate,hydro; public NativeArray<Color32> o0,o1,o2; public float iceCap; public void Execute(int i){ float land=tect[i].r/255f; if(land<0.5f){o0[i]=o1[i]=o2[i]=new Color32();return;} float t=climate[i].r/255f,m=climate[i].g/255f,h=tect[i].g/255f,mtn=tect[i].b/255f,wet=hydro[i].b/255f; float jungle=math.saturate((t-0.55f)*2f)*math.saturate((m-0.65f)*2f); float desert=math.saturate((1f-m)*1.6f)*math.saturate((t-0.45f)*1.8f); float sav=math.saturate((t-0.5f)*1.8f)*(1f-math.abs(m-0.5f)*2f); float tg=math.saturate(1f-math.abs(t-0.52f)*2f); float tf=math.saturate((1f-math.abs(t-0.5f)*2f)*(m)); float ta=math.saturate((1f-math.abs(t-0.35f)*3f)*m); float tun=math.saturate((0.4f-t)*3f); float pol=math.saturate((0.25f-t)*4f); float marsh=wet*m; float snow=math.saturate((0.32f-t)*3f + h*0.3f + mtn*0.25f + iceCap*0.4f); float alp=math.saturate((mtn*0.7f+h*0.5f)-m*0.25f); o0[i]=new Color32(ToByte(jungle),ToByte(desert),ToByte(sav),ToByte(tg)); o1[i]=new Color32(ToByte(tf),ToByte(ta),ToByte(tun),ToByte(pol)); o2[i]=new Color32(ToByte(marsh),ToByte(snow),ToByte(alp),0);} }
}
