// Assets/Scripts/Trade/TradeManager.cs
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Central manager for the trade system. Tracks global unlock state and which civilizations
/// have trade enabled. Provides helpers for UI and gameplay code to query availability.
/// </summary>
public class TradeManager : MonoBehaviour
{
    public static TradeManager Instance { get; private set; }

    [Tooltip("When true, trade is available for all civilizations.")]
    public bool globalTradeEnabled = false;

    [Header("City Trade Defaults")]
    [Tooltip("Maximum tile distance/path length for a normal city trade route.")]
    public int maxCityTradeRange = TradeRoute.DEFAULT_MAX_CITY_TRADE_RANGE;
    [Tooltip("Minimum gold generated by a valid city trade route before population and destination-gold bonuses.")]
    public int baseCityTradeGold = TradeRoute.BASE_CITY_TRADE_GOLD_PER_TURN;
    [Tooltip("Default chance that a city trade route is raided each turn before modifiers.")]
    [Range(0f, 1f)]
    public float baseCityTradeRaidChance = TradeRoute.DEFAULT_RAID_CHANCE;

    // Track specific civilizations that have trade unlocked (if global not enabled)
    private HashSet<Civilization> civsWithTrade = new HashSet<Civilization>();

    public event Action OnGlobalTradeEnabled;
    public event Action<Civilization> OnCivilizationTradeEnabled;

    void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }

    /// <summary>
    /// Unlock trade globally for all civilizations.
    /// </summary>
    public void UnlockGlobalTrade()
    {
        if (globalTradeEnabled) return;
        globalTradeEnabled = true;
        OnGlobalTradeEnabled?.Invoke();
        UIManager.Instance?.ShowNotification("Global trade system unlocked!");
    }

    /// <summary>
    /// Unlock trade for a specific civilization.
    /// </summary>
    public void UnlockTradeForCivilization(Civilization civ)
    {
        if (civ == null) return;
        if (globalTradeEnabled)
        {
            // Already globally enabled - ensure civ flag is consistent
            civ.tradeEnabled = true;
            OnCivilizationTradeEnabled?.Invoke(civ);
            return;
        }

        if (civsWithTrade.Contains(civ)) return;
        civsWithTrade.Add(civ);
        civ.tradeEnabled = true; // keep per-civ flag in sync
        OnCivilizationTradeEnabled?.Invoke(civ);
        UIManager.Instance?.ShowNotification($"{civ.civData.civName} has unlocked trade!");
    }

    /// <summary>
    /// Returns true when trade is available for the given civilization (either global or per-civ).
    /// </summary>
    public bool IsTradeEnabledForCivilization(Civilization civ)
    {
        if (globalTradeEnabled) return true;
        if (civ == null) return false;
        if (civ.tradeEnabled) return true;
        return civsWithTrade.Contains(civ);
    }

    public static int CurrentMaxCityTradeRange =>
        Instance != null ? Mathf.Max(1, Instance.maxCityTradeRange) : TradeRoute.DEFAULT_MAX_CITY_TRADE_RANGE;

    public static int CurrentBaseCityTradeGold =>
        Instance != null ? Mathf.Max(0, Instance.baseCityTradeGold) : TradeRoute.BASE_CITY_TRADE_GOLD_PER_TURN;

    public static float CurrentBaseCityTradeRaidChance =>
        Instance != null ? Mathf.Clamp01(Instance.baseCityTradeRaidChance) : TradeRoute.DEFAULT_RAID_CHANCE;
}
