// Assets/Scripts/Trade/TradeManager.cs
using System;
using System.Collections.Generic;
using UnityEngine;

public enum SpaceTradeRangeScope
{
    Disabled = 0,
    EarthMoon = 1,
    SolarSystem = 2,
    Interstellar = 3
}

/// <summary>
/// Central manager for the trade system. Tracks global unlock state and which civilizations
/// have trade enabled. Provides helpers for UI and gameplay code to query availability.
/// </summary>
public class TradeManager : MonoBehaviour
{
    public static TradeManager Instance { get; private set; }

    [Tooltip("When true, trade is available for all civilizations.")]
    public bool globalTradeEnabled = false;

    [Header("City Trade Defaults")]
    [Tooltip("Maximum tile distance/path length for a normal city trade route.")]
    public int maxCityTradeRange = TradeRoute.DEFAULT_MAX_CITY_TRADE_RANGE;
    [Tooltip("Minimum gold generated by a valid city trade route before population and destination-gold bonuses.")]
    public int baseCityTradeGold = TradeRoute.BASE_CITY_TRADE_GOLD_PER_TURN;
    [Tooltip("Default chance that a city trade route is raided each turn before modifiers.")]
    [Range(0f, 1f)]
    public float baseCityTradeRaidChance = TradeRoute.DEFAULT_RAID_CHANCE;
    [Tooltip("Maximum tile distance for airport-to-airport trade on the same planet.")]
    public int maxAirportTradeRange = TradeRoute.DEFAULT_MAX_AIRPORT_TRADE_RANGE;

    [Header("Space Trade Defaults")]
    [Tooltip("Current reach for spaceport-to-spaceport trade. Gate this upward from tech/culture unlocks.")]
    public SpaceTradeRangeScope spaceTradeRangeScope = SpaceTradeRangeScope.EarthMoon;

    // Track specific civilizations that have trade unlocked (if global not enabled)
    private HashSet<Civilization> civsWithTrade = new HashSet<Civilization>();

    public event Action OnGlobalTradeEnabled;
    public event Action<Civilization> OnCivilizationTradeEnabled;

    void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }

    /// <summary>
    /// Unlock trade globally for all civilizations.
    /// </summary>
    public void UnlockGlobalTrade()
    {
        if (globalTradeEnabled) return;
        globalTradeEnabled = true;
        OnGlobalTradeEnabled?.Invoke();
        UIManager.Instance?.ShowNotification("Global trade system unlocked!");
    }

    /// <summary>
    /// Unlock trade for a specific civilization.
    /// </summary>
    public void UnlockTradeForCivilization(Civilization civ)
    {
        if (civ == null) return;
        if (globalTradeEnabled)
        {
            // Already globally enabled - ensure civ flag is consistent
            civ.tradeEnabled = true;
            OnCivilizationTradeEnabled?.Invoke(civ);
            return;
        }

        if (civsWithTrade.Contains(civ)) return;
        civsWithTrade.Add(civ);
        civ.tradeEnabled = true; // keep per-civ flag in sync
        OnCivilizationTradeEnabled?.Invoke(civ);
        UIManager.Instance?.ShowNotification($"{civ.civData.civName} has unlocked trade!");
    }

    /// <summary>
    /// Returns true when trade is available for the given civilization (either global or per-civ).
    /// </summary>
    public bool IsTradeEnabledForCivilization(Civilization civ)
    {
        if (globalTradeEnabled) return true;
        if (civ == null) return false;
        if (civ.tradeEnabled) return true;
        return civsWithTrade.Contains(civ);
    }

    public static int CurrentMaxCityTradeRange =>
        Instance != null ? Mathf.Max(1, Instance.maxCityTradeRange) : TradeRoute.DEFAULT_MAX_CITY_TRADE_RANGE;

    public static int CurrentBaseCityTradeGold =>
        Instance != null ? Mathf.Max(0, Instance.baseCityTradeGold) : TradeRoute.BASE_CITY_TRADE_GOLD_PER_TURN;

    public static float CurrentBaseCityTradeRaidChance =>
        Instance != null ? Mathf.Clamp01(Instance.baseCityTradeRaidChance) : TradeRoute.DEFAULT_RAID_CHANCE;

    public static int CurrentMaxAirportTradeRange =>
        Instance != null ? Mathf.Max(1, Instance.maxAirportTradeRange) : TradeRoute.DEFAULT_MAX_AIRPORT_TRADE_RANGE;

    public static SpaceTradeRangeScope CurrentSpaceTradeRangeScope =>
        Instance != null ? Instance.spaceTradeRangeScope : SpaceTradeRangeScope.EarthMoon;

    public void SetSpaceTradeRangeScope(SpaceTradeRangeScope scope)
    {
        spaceTradeRangeScope = scope;
    }

    public static bool CanSpacePortTradeBetween(City source, City destination)
    {
        if (source == null || destination == null) return false;
        if (!source.HasOperationalSpaceport() || !destination.HasOperationalSpaceport()) return false;

        SpaceTradeRangeScope scope = CurrentSpaceTradeRangeScope;
        if (scope == SpaceTradeRangeScope.Disabled) return false;
        if (source.planetIndex == destination.planetIndex) return true;
        if (scope >= SpaceTradeRangeScope.SolarSystem) return true;
        if (scope == SpaceTradeRangeScope.EarthMoon)
            return IsEarthMoonOrOrbitTrade(source.planetIndex, destination.planetIndex);

        return false;
    }

    public static bool CanSpaceTradeBetweenPlanets(int originPlanetIndex, int destinationPlanetIndex)
    {
        if (originPlanetIndex == destinationPlanetIndex) return false;
        SpaceTradeRangeScope scope = CurrentSpaceTradeRangeScope;
        if (scope == SpaceTradeRangeScope.Disabled) return false;
        if (scope >= SpaceTradeRangeScope.SolarSystem) return true;
        return scope == SpaceTradeRangeScope.EarthMoon
               && IsEarthMoonOrOrbitTrade(originPlanetIndex, destinationPlanetIndex);
    }

    private static bool IsEarthMoonOrOrbitTrade(int originPlanetIndex, int destinationPlanetIndex)
    {
        var planetData = GameManager.Instance != null ? GameManager.Instance.GetPlanetData() : null;
        if (planetData == null || planetData.Count == 0)
            return originPlanetIndex == 0 && destinationPlanetIndex == 0;

        bool originAllowed = IsEarthMoonOrOrbitBody(originPlanetIndex, planetData);
        bool destinationAllowed = IsEarthMoonOrOrbitBody(destinationPlanetIndex, planetData);
        return originAllowed && destinationAllowed;
    }

    private static bool IsEarthMoonOrOrbitBody(int planetIndex, Dictionary<int, GameManager.PlanetData> planetData)
    {
        if (!planetData.TryGetValue(planetIndex, out var body) || body == null)
            return planetIndex == 0;

        string name = body.planetName ?? string.Empty;
        if (planetIndex == 0) return true;
        if (name.IndexOf("earth", StringComparison.OrdinalIgnoreCase) >= 0) return true;
        if (name.IndexOf("luna", StringComparison.OrdinalIgnoreCase) >= 0) return true;
        if (name.IndexOf("moon", StringComparison.OrdinalIgnoreCase) >= 0 && IsMoonOfEarth(body, planetData)) return true;
        if (name.IndexOf("orbit", StringComparison.OrdinalIgnoreCase) >= 0 && name.IndexOf("earth", StringComparison.OrdinalIgnoreCase) >= 0) return true;

        return false;
    }

    private static bool IsMoonOfEarth(GameManager.PlanetData moon, Dictionary<int, GameManager.PlanetData> planetData)
    {
        foreach (var kvp in planetData)
        {
            var planet = kvp.Value;
            if (planet == null || planet.moonNames == null) continue;
            if (string.IsNullOrEmpty(planet.planetName) || planet.planetName.IndexOf("earth", StringComparison.OrdinalIgnoreCase) < 0) continue;

            foreach (string moonName in planet.moonNames)
            {
                if (!string.IsNullOrEmpty(moonName)
                    && string.Equals(moonName, moon.planetName, StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }

        return false;
    }
}
